# Generated by Django 5.1.15 on 2026-09-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador"),
                    ("TABLE_OFFICIAL", "Mesa Arbitral"),
                    ("REFEREE", "Árbitro"),
                    ("COACH", "Entrenador"),
                    ("FAN", "Aficionado / Espectador"),
                ],
                default="FAN",
                max_length=20,
                verbose_name="Rol de Usuario",
            ),
        ),
    ]
