# Generated by Django 5.1.15 on 2026-08-19 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="League",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Nombre de la Liga"
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=170, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="leagues/", verbose_name="Logo"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Liga",
                "verbose_name_plural": "Ligas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Apellidos"),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Nacimiento"
                    ),
                ),
                (
                    "height_cm",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Altura (cm)"
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Peso (kg)",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("PG", "Base (1)"),
                            ("SG", "Escolta (2)"),
                            ("SF", "Alero (3)"),
                            ("PF", "Ala-Pívot (4)"),
                            ("C", "Pívot (5)"),
                        ],
                        default="SF",
                        max_length=3,
                        verbose_name="Posición Principal",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="players/", verbose_name="Foto"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Ficha Activa"),
                ),
            ],
            options={
                "verbose_name": "Jugador",
                "verbose_name_plural": "Jugadores",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Temporada (ej. 2025/2026)"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Fecha de Inicio")),
                ("end_date", models.DateField(verbose_name="Fecha de Finalización")),
                (
                    "is_current",
                    models.BooleanField(default=True, verbose_name="Temporada Actual"),
                ),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasons",
                        to="teams.league",
                        verbose_name="Liga",
                    ),
                ),
            ],
            options={
                "verbose_name": "Temporada",
                "verbose_name_plural": "Temporadas",
                "ordering": ["-start_date"],
                "unique_together": {("league", "name")},
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Nombre del Equipo"
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=170, unique=True)),
                (
                    "acronym",
                    models.CharField(
                        max_length=4, verbose_name="Acrónimo (3-4 letras, ej. RMB, FCB)"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="teams/", verbose_name="Escudo"
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#FF6600",
                        max_length=7,
                        verbose_name="Color Principal (HEX)",
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#1E293B",
                        max_length=7,
                        verbose_name="Color Secundario (HEX)",
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Ciudad"),
                ),
                (
                    "arena_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Pabellón / Cancha"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coach",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coached_teams",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Primer Entrenador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipo",
                "verbose_name_plural": "Equipos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TeamMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jersey_number",
                    models.PositiveIntegerField(verbose_name="Dorsal (0-99)"),
                ),
                (
                    "is_captain",
                    models.BooleanField(default=False, verbose_name="Capitán"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Activo en plantilla"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_memberships",
                        to="teams.player",
                        verbose_name="Jugador",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_memberships",
                        to="teams.season",
                        verbose_name="Temporada",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_memberships",
                        to="teams.team",
                        verbose_name="Equipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ficha de Plantilla",
                "verbose_name_plural": "Fichas de Plantillas",
                "ordering": ["jersey_number"],
                "unique_together": {
                    ("team", "season", "jersey_number"),
                    ("team", "season", "player"),
                },
            },
        ),
    ]
