# Generated by Django 5.1.15 on 2026-09-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="position",
            field=models.CharField(
                choices=[
                    ("PG", "Base"),
                    ("SG", "Escolta"),
                    ("SF", "Alero"),
                    ("PF", "Ala-Pívot"),
                    ("C", "Pívot"),
                ],
                default="SF",
                max_length=3,
                verbose_name="Posición Principal",
            ),
        ),
    ]
