# Generated by Django 5.1.15 on 2026-08-19 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("matches", "0001_initial"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerMatchStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "minutes_played",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Minutos Jugados"
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Puntos Totales"
                    ),
                ),
                (
                    "field_goals_made",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tiros de Campo Anotados (T2/T3)"
                    ),
                ),
                (
                    "field_goals_attempted",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tiros de Campo Intentados"
                    ),
                ),
                (
                    "three_points_made",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Triples Anotados"
                    ),
                ),
                (
                    "three_points_attempted",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Triples Intentados"
                    ),
                ),
                (
                    "free_throws_made",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tiros Libres Anotados"
                    ),
                ),
                (
                    "free_throws_attempted",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tiros Libres Intentados"
                    ),
                ),
                (
                    "rebounds_off",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Rebotes Ofensivos"
                    ),
                ),
                (
                    "rebounds_def",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Rebotes Defensivos"
                    ),
                ),
                (
                    "assists",
                    models.PositiveIntegerField(default=0, verbose_name="Asistencias"),
                ),
                (
                    "steals",
                    models.PositiveIntegerField(default=0, verbose_name="Robos"),
                ),
                (
                    "turnovers",
                    models.PositiveIntegerField(default=0, verbose_name="Pérdidas"),
                ),
                (
                    "blocks_made",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tapones a Favor"
                    ),
                ),
                (
                    "blocks_received",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tapones Recibidos"
                    ),
                ),
                (
                    "fouls_committed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Faltas Personales Cometidas"
                    ),
                ),
                (
                    "fouls_received",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Faltas Recibidas"
                    ),
                ),
                (
                    "valuation_pir",
                    models.IntegerField(default=0, verbose_name="Valoración (PIR)"),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_stats",
                        to="matches.match",
                        verbose_name="Partido",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_stats",
                        to="teams.player",
                        verbose_name="Jugador",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_match_stats",
                        to="teams.team",
                        verbose_name="Equipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estadística de Jugador por Partido",
                "verbose_name_plural": "Estadísticas de Jugadores por Partido",
                "ordering": ["-points", "-valuation_pir"],
                "unique_together": {("match", "player")},
            },
        ),
        migrations.CreateModel(
            name="Standing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "games_played",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Partidos Jugados (PJ)"
                    ),
                ),
                (
                    "wins",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Victorias (PG)"
                    ),
                ),
                (
                    "losses",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Derrotas (PP)"
                    ),
                ),
                (
                    "points_for",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Puntos a Favor (PF)"
                    ),
                ),
                (
                    "points_against",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Puntos en Contra (PC)"
                    ),
                ),
                (
                    "points_diff",
                    models.IntegerField(
                        default=0, verbose_name="Diferencia de Puntos (DIF)"
                    ),
                ),
                (
                    "league_points",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Puntos Clasificación (PTS)"
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standings",
                        to="teams.season",
                        verbose_name="Temporada",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standings",
                        to="teams.team",
                        verbose_name="Equipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clasificación",
                "verbose_name_plural": "Clasificaciones",
                "ordering": ["-league_points", "-points_diff", "-points_for"],
                "unique_together": {("season", "team")},
            },
        ),
    ]
