# Generated by Django on 2026-09-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playermatchstat",
            name="is_on_court",
            field=models.BooleanField(default=False, verbose_name="En Pista"),
        ),
        migrations.AddField(
            model_name="playermatchstat",
            name="is_starter",
            field=models.BooleanField(default=False, verbose_name="Titular / Quinteto Inicial"),
        ),
    ]
