# Generated by Django 5.1.15 on 2026-08-19 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "round_number",
                    models.PositiveIntegerField(default=1, verbose_name="Jornada"),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(verbose_name="Fecha y Hora Programada"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Pabellón / Ubicación"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Programado"),
                            ("LIVE", "En Juego"),
                            ("FINISHED", "Finalizado"),
                            ("SUSPENDED", "Suspendido"),
                        ],
                        default="SCHEDULED",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "current_period",
                    models.CharField(
                        choices=[
                            ("NS", "Por Comenzar"),
                            ("Q1", "1º Cuarto"),
                            ("Q2", "2º Cuarto"),
                            ("HT", "Descanso"),
                            ("Q3", "3º Cuarto"),
                            ("Q4", "4º Cuarto"),
                            ("OT1", "1ª Prórroga"),
                            ("OT2", "2ª Prórroga"),
                            ("END", "Partido Concluido"),
                        ],
                        default="NS",
                        max_length=5,
                        verbose_name="Periodo Actual",
                    ),
                ),
                (
                    "game_clock",
                    models.CharField(
                        default="10:00", max_length=10, verbose_name="Reloj de Juego"
                    ),
                ),
                (
                    "home_score",
                    models.PositiveIntegerField(default=0, verbose_name="Puntos Local"),
                ),
                (
                    "away_score",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Puntos Visitante"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_matches",
                        to="teams.team",
                        verbose_name="Equipo Visitante",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_matches",
                        to="teams.team",
                        verbose_name="Equipo Local",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="teams.season",
                        verbose_name="Temporada",
                    ),
                ),
                (
                    "table_official",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="officiated_matches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Mesa Arbitral Asignada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partido",
                "verbose_name_plural": "Partidos",
                "ordering": ["scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="DigitalScoreSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(
                        default=False, verbose_name="Acta Oficial Cerrada"
                    ),
                ),
                (
                    "referee_signature",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="Firma / Nombre Árbitro Principal",
                    ),
                ),
                (
                    "table_official_signature",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Firma Mesa Arbitral"
                    ),
                ),
                (
                    "incidents_report",
                    models.TextField(blank=True, verbose_name="Informe de Incidencias"),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha y Hora de Cierre"
                    ),
                ),
                (
                    "match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoresheet",
                        to="matches.match",
                        verbose_name="Partido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acta Digital",
                "verbose_name_plural": "Actas Digitales",
            },
        ),
        migrations.CreateModel(
            name="MatchEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("NS", "Por Comenzar"),
                            ("Q1", "1º Cuarto"),
                            ("Q2", "2º Cuarto"),
                            ("HT", "Descanso"),
                            ("Q3", "3º Cuarto"),
                            ("Q4", "4º Cuarto"),
                            ("OT1", "1ª Prórroga"),
                            ("OT2", "2ª Prórroga"),
                            ("END", "Partido Concluido"),
                        ],
                        max_length=5,
                        verbose_name="Periodo",
                    ),
                ),
                (
                    "game_clock",
                    models.CharField(
                        default="10:00", max_length=10, verbose_name="Minuto/Reloj"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("1PT_MADE", "Tiro Libre Anotado (+1)"),
                            ("1PT_MISS", "Tiro Libre Fallado"),
                            ("2PT_MADE", "Canasta de 2 Anotada (+2)"),
                            ("2PT_MISS", "Tiro de 2 Fallado"),
                            ("3PT_MADE", "Triple Anotado (+3)"),
                            ("3PT_MISS", "Triple Fallado"),
                            ("REB_OFF", "Rebote Ofensivo"),
                            ("REB_DEF", "Rebote Defensivo"),
                            ("AST", "Asistencia"),
                            ("STL", "Robo de Balón"),
                            ("TOV", "Pérdida de Balón"),
                            ("BLK", "Tapón"),
                            ("PF", "Falta Personal"),
                            ("TF", "Falta Técnica"),
                            ("UF", "Falta Antideportiva"),
                            ("TO", "Tiempo Muerto"),
                            ("SUB", "Sustitución"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Evento",
                    ),
                ),
                (
                    "points",
                    models.SmallIntegerField(default=0, verbose_name="Puntos Sumados"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Descripción"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="matches.match",
                        verbose_name="Partido",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="match_events",
                        to="teams.player",
                        verbose_name="Jugador",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_events",
                        to="teams.team",
                        verbose_name="Equipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de Partido",
                "verbose_name_plural": "Eventos de Partidos",
                "ordering": ["-created_at"],
            },
        ),
    ]
