# Generated by Django on 2026-09-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="timekeeper",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timekeeper_matches",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Mesa Arbitral - Cronometrador",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="table_official",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="officiated_matches",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Mesa Arbitral - Anotador",
            ),
        ),
        migrations.AddField(
            model_name="digitalscoresheet",
            name="timekeeper_signature",
            field=models.CharField(
                blank=True,
                max_length=150,
                verbose_name="Firma Cronometrador (Mesa Arbitral)",
            ),
        ),
        migrations.AlterField(
            model_name="digitalscoresheet",
            name="table_official_signature",
            field=models.CharField(
                blank=True,
                max_length=150,
                verbose_name="Firma Anotador (Mesa Arbitral)",
            ),
        ),
    ]
