# Generated by Django 5.1.15 on 2026-09-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0002_match_timekeeper_digitalscoresheet_timekeeper_signature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("1PT_MADE", "Tiro Libre Anotado (+1)"),
                    ("1PT_MISS", "Tiro Libre Fallado"),
                    ("2PT_MADE", "Canasta de 2 Anotada (+2)"),
                    ("2PT_MISS", "Tiro de 2 Fallado"),
                    ("3PT_MADE", "Triple Anotado (+3)"),
                    ("3PT_MISS", "Triple Fallado"),
                    ("REB_OFF", "Rebote Ofensivo"),
                    ("REB_DEF", "Rebote Defensivo"),
                    ("AST", "Asistencia"),
                    ("STL", "Robo de Balón"),
                    ("TOV", "Pérdida de Balón"),
                    ("BLK", "Tapón"),
                    ("PF", "Falta Personal"),
                    ("TF", "Falta Técnica"),
                    ("UF", "Falta Antideportiva"),
                    ("TO", "Tiempo Muerto"),
                    ("SUB", "Sustitución"),
                    ("STARTING_FIVE", "Quinteto Inicial"),
                    ("CORRECTION", "Corrección de Marcador"),
                    ("PERIOD", "Cambio de Periodo"),
                ],
                max_length=20,
                verbose_name="Tipo de Evento",
            ),
        ),
    ]
