# Generated by Django 5.1.15 on 2026-09-18 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("matches", "0003_alter_matchevent_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="referee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refereed_matches",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Árbitro Principal",
            ),
        ),
    ]
