# Generated by Django 5.1.15 on 2026-09-18 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("matches", "0004_match_referee"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="second_referee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assistant_refereed_matches",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Árbitro Auxiliar",
            ),
        ),
        migrations.AddField(
            model_name="digitalscoresheet",
            name="second_referee_signature",
            field=models.CharField(
                blank=True,
                max_length=150,
                verbose_name="Firma / Nombre Árbitro Auxiliar",
            ),
        ),
    ]
