# Generated by Django 5.1.15 on 2026-09-27 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "matches",
            "0005_match_second_referee_digitalscoresheet_second_referee_signature",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="referee",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "REFEREE"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refereed_matches",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Árbitro Principal",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="second_referee",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "REFEREE"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assistant_refereed_matches",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Árbitro Auxiliar",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="table_official",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "TABLE_OFFICIAL"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="officiated_matches",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Mesa Arbitral - Anotador",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="timekeeper",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "TABLE_OFFICIAL"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timekeeper_matches",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Mesa Arbitral - Cronometrador",
            ),
        ),
    ]
